/*

	SFX_00

	Sound Effect File.

	Info:
		Length			:	15
		Bank			:	0
		Priority		:	0
		Channels used	:	Duty channel 2 & Noise channel

	This file was generated by hammer2cbt

*/
#ifndef __SFX_00_h_INCLUDE
#define __SFX_00_h_INCLUDE
#define SFX_00_Length 15
#define SFX_00_Bank 0
#define SFX_00_CH_Used 255
#define SFX_00_Priority 0
#define CBTFX_PLAY_SFX_00 CBTFX_init(&SFX_00[0][0], 15, 0, 255)
extern const unsigned char SFX_00[15][CBTFX_LENGTH];
#endif