/*

	SFX_06

	Sound Effect File.

	Info:
		Length	:	20
		Bank	:	0

	This file was generated by hammer2cbt

*/
#ifndef __SFX_06_h_INCLUDE
#define __SFX_06_h_INCLUDE
#define SFX_06_Length 20
#define SFX_06_Bank 0
extern const unsigned char SFX_06[20][CBTFX_LENGTH];
#endif