/*

	SFX_05

	Sound Effect File.

	Info:
		Length	:	15
		Bank	:	0

	This file was generated by hammer2cbt

*/
#ifndef __SFX_05_h_INCLUDE
#define __SFX_05_h_INCLUDE
#define SFX_05_Length 15
#define SFX_05_Bank 0
extern const unsigned char SFX_05[15][CBTFX_LENGTH];
#endif