/*

	SFX_05

	Sound Effect File.

	Info:
		Length			:	16
		Bank			:	0
		Priority		:	0
		Channels used	:	Duty channel 2 & Noise channel

	This file was generated by hammer2cbt

*/
#ifndef __SFX_05_h_INCLUDE
#define __SFX_05_h_INCLUDE
#define SFX_05_Length 16
#define SFX_05_Bank 0
#define SFX_05_CH_Used 255
#define SFX_05_Priority 0
#define CBTFX_PLAY_SFX_05 CBTFX_init(&SFX_05[0][0], 16, 0, 255)
extern const unsigned char SFX_05[16][CBTFX_LENGTH];
#endif