/*

	SFX_06

	Sound Effect File.

	Info:
		Length			:	21
		Bank			:	0
		Priority		:	0
		Channels used	:	Duty channel 2 & Noise channel

	This file was generated by hammer2cbt

*/
#define SFX_06_Length 21
#define SFX_06_Bank 0
#define SFX_06_CH_Used 255
#define SFX_06_Priority 0
#define CBTFX_PLAY_SFX_06 CBTFX_init(&SFX_06[0][0], 21, 0, 255)
#include "../cbtfx.h"

const unsigned char SFX_06[21][CBTFX_LENGTH] = {
	CBTFX_FRAME(1, 17, 15, 2, FX_Gs2, 17, 15, 80),
	CBTFX_FRAME(1, 17, 15, 2, FX_E_2, 17, 8, 128),
	CBTFX_FRAME(1, 17, 15, 2, FX_D_2, 17, 6, 48),
	CBTFX_FRAME(1, 17, 15, 2, FX_C_2, 17, 4, 96),
	CBTFX_FRAME(1, 17, 15, 2, FX_As1, 17, 2, 112),
	CBTFX_FRAME(1, 17, 15, 2, FX_A_1, 17, 2, 64),
	CBTFX_FRAME(1, 17, 15, 2, FX_As1, 17, 2, 96),
	CBTFX_FRAME(1, 17, 15, 2, FX_C_2, 17, 1, 112),
	CBTFX_FRAME(1, 17, 14, 2, FX_D_2, 17, 1, 80),
	CBTFX_FRAME(1, 17, 12, 2, FX_E_2, 17, 1, 32),
	CBTFX_FRAME(1, 17, 8, 2, FX_Gs2, 0, 0, 0),
	CBTFX_FRAME(1, 17, 4, 2, FX_C_3, 0, 0, 0),
	CBTFX_FRAME(1, 17, 2, 2, FX_E_3, 0, 0, 0),
	CBTFX_FRAME(1, 16, 3, 2, FX_As1, 0, 0, 0),
	CBTFX_FRAME(1, 16, 3, 2, FX_C_2, 0, 0, 0),
	CBTFX_FRAME(1, 16, 3, 2, FX_D_2, 0, 0, 0),
	CBTFX_FRAME(1, 16, 2, 2, FX_E_2, 0, 0, 0),
	CBTFX_FRAME(1, 16, 2, 2, FX_Gs2, 0, 0, 0),
	CBTFX_FRAME(1, 16, 1, 2, FX_C_3, 0, 0, 0),
	CBTFX_FRAME(1, 16, 1, 2, FX_E_3, 0, 0, 0)
};