/*

		SFX_08

		Sound Effect File.
		
		Info:
			Length			:	20
			Priority		:	0
			Channels used	:	Noise channel
		
		This file was generated by hammer2cbt

	*/
	#ifndef __SFX_08_h_INCLUDE
#define __SFX_08_h_INCLUDE
#define CBTFX_PLAY_SFX_08 CBTFX_init(&SFX_08[0])
extern const unsigned char SFX_08[];
#endif