/*

		SFX_06

		Sound Effect File.
		
		Info:
			Length			:	20
			Priority		:	0
			Channels used	:	Duty channel 2 & Noise channel
		
		This file was generated by hammer2cbt

	*/
	#ifndef __SFX_06_h_INCLUDE
#define __SFX_06_h_INCLUDE
#define CBTFX_PLAY_SFX_06 CBTFX_init(&SFX_06[0])
extern const unsigned char SFX_06[];
#endif