/*

	SFX_06

	Sound Effect File.

	Info:
		Length			:	21
		Bank			:	0
		Priority		:	0
		Channels used	:	Duty channel 2 & Noise channel

	This file was generated by hammer2cbt

*/
#ifndef __SFX_06_h_INCLUDE
#define __SFX_06_h_INCLUDE
#define SFX_06_Length 21
#define SFX_06_Bank 0
#define SFX_06_CH_Used 255
#define SFX_06_Priority 0
#define CBTFX_PLAY_SFX_06 CBTFX_init(&SFX_06[0][0], 21, 0, 255)
extern const unsigned char SFX_06[21][CBTFX_LENGTH];
#endif