/*

		SFX_07

		Sound Effect File.
		
		Info:
			Length			:	31
			Priority		:	0
			Channels used	:	Duty channel 2
		
		This file was generated by hammer2cbt

	*/
	#ifndef __SFX_07_h_INCLUDE
#define __SFX_07_h_INCLUDE
#define CBTFX_PLAY_SFX_07 CBTFX_init(&SFX_07[0])
extern const unsigned char SFX_07[];
#endif