/*

		SFX_08

		Sound Effect File.
		
		Info:
			Length			:	20
			Priority		:	0
			Channels used	:	Noise channel
		
		This file was generated by hammer2cbt

	*/
	const unsigned char SFX_08[] = {
48, // Header
20,
1, 136, 15, 64, 1, 136, 15, 80, 1, 136, 15, 96, 1, 136, 15, 112, 1, 136, 15, 128, 1, 136, 5, 64, 1, 136, 5, 80, 1, 136, 5, 96, 1, 136, 5, 112, 1, 136, 5, 128, 1, 8, 3, 64, 1, 8, 3, 80, 1, 8, 3, 96, 1, 8, 3, 112, 1, 8, 3, 128, 1, 128, 2, 64, 1, 128, 2, 80, 1, 128, 2, 96, 1, 128, 2, 112, 1, 128, 2, 128
};