/*

	SFX_04

	Sound Effect File.

	Info:
		Length	:	12
		Bank	:	0

	This file was generated by hammer2cbt

*/
#ifndef __SFX_04_h_INCLUDE
#define __SFX_04_h_INCLUDE
#define SFX_04_Length 12
#define SFX_04_Bank 0
extern const unsigned char SFX_04[12][CBTFX_LENGTH];
#endif