/*

	SFX_07

	Sound Effect File.

	Info:
		Length	:	31
		Bank	:	0

	This file was generated by hammer2cbt

*/
#ifndef __SFX_07_h_INCLUDE
#define __SFX_07_h_INCLUDE
#define SFX_07_Length 31
#define SFX_07_Bank 0
extern const unsigned char SFX_07[31][CBTFX_LENGTH];
#endif