/*

	SFX_03

	Sound Effect File.

	Info:
		Length	:	24
		Bank	:	0

	This file was generated by hammer2cbt

*/
#define SFX_03_Length 24
#define SFX_03_Bank 0
#include "../cbtfx.h"

const unsigned char SFX_03[24][CBTFX_LENGTH] = {
	CBTFX_FRAME(1, 17, 15, 0, FX_E_5, 0, 0, 0),
	CBTFX_FRAME(3, 17, 15, 2, FX_E_4, 0, 0, 0),
	CBTFX_FRAME(1, 17, 15, 0, FX_Fs5, 0, 0, 0),
	CBTFX_FRAME(3, 17, 15, 2, FX_Fs4, 0, 0, 0),
	CBTFX_FRAME(1, 17, 15, 0, FX_Gs5, 0, 0, 0),
	CBTFX_FRAME(3, 17, 15, 2, FX_Gs4, 0, 0, 0),
	CBTFX_FRAME(1, 17, 5, 0, FX_E_5, 0, 0, 0),
	CBTFX_FRAME(3, 17, 5, 2, FX_E_4, 0, 0, 0),
	CBTFX_FRAME(1, 17, 5, 0, FX_Fs5, 0, 0, 0),
	CBTFX_FRAME(3, 17, 5, 2, FX_Fs4, 0, 0, 0),
	CBTFX_FRAME(1, 17, 5, 0, FX_Gs5, 0, 0, 0),
	CBTFX_FRAME(3, 17, 5, 2, FX_Gs4, 0, 0, 0),
	CBTFX_FRAME(1, 17, 2, 0, FX_E_5, 0, 0, 0),
	CBTFX_FRAME(3, 17, 2, 2, FX_E_4, 0, 0, 0),
	CBTFX_FRAME(1, 17, 2, 0, FX_Fs5, 0, 0, 0),
	CBTFX_FRAME(3, 17, 2, 2, FX_Fs4, 0, 0, 0),
	CBTFX_FRAME(1, 17, 2, 0, FX_Gs5, 0, 0, 0),
	CBTFX_FRAME(3, 17, 2, 2, FX_Gs4, 0, 0, 0),
	CBTFX_FRAME(1, 16, 1, 0, FX_E_5, 0, 0, 0),
	CBTFX_FRAME(3, 16, 1, 2, FX_E_4, 0, 0, 0),
	CBTFX_FRAME(1, 16, 1, 0, FX_Fs5, 0, 0, 0),
	CBTFX_FRAME(3, 16, 1, 2, FX_Fs4, 0, 0, 0),
	CBTFX_FRAME(1, 16, 1, 0, FX_Gs5, 0, 0, 0),
	CBTFX_FRAME(3, 16, 1, 2, FX_Gs4, 0, 0, 0)
};