/*

	SFX_02

	Sound Effect File.

	Info:
		Length	:	12
		Bank	:	0

	This file was generated by hammer2cbt

*/
#ifndef __SFX_02_h_INCLUDE
#define __SFX_02_h_INCLUDE
#define SFX_02_Length 12
#define SFX_02_Bank 0
extern const unsigned char SFX_02[12][CBTFX_LENGTH];
#endif