/*

	SFX_02

	Sound Effect File.

	Info:
		Length			:	13
		Bank			:	0
		Priority		:	0
		Channels used	:	Duty channel 2 & Noise channel

	This file was generated by hammer2cbt

*/
#define SFX_02_Length 13
#define SFX_02_Bank 0
#define SFX_02_CH_Used 255
#define SFX_02_Priority 0
#define CBTFX_PLAY_SFX_02 CBTFX_init(&SFX_02[0][0], 13, 0, 255)
#include "../cbtfx.h"

const unsigned char SFX_02[13][CBTFX_LENGTH] = {
	CBTFX_FRAME(1, 17, 15, 1, FX_C_5, 17, 8, 80),
	CBTFX_FRAME(3, 17, 15, 2, FX_C_4, 17, 3, 48),
	CBTFX_FRAME(1, 17, 15, 1, FX_E_5, 17, 3, 32),
	CBTFX_FRAME(3, 17, 15, 2, FX_E_4, 17, 2, 32),
	CBTFX_FRAME(2, 17, 8, 1, FX_E_4, 17, 2, 32),
	CBTFX_FRAME(2, 17, 4, 0, FX_E_4, 17, 1, 16),
	CBTFX_FRAME(1, 1, 6, 1, FX_C_5, 0, 0, 0),
	CBTFX_FRAME(3, 1, 6, 2, FX_C_4, 0, 0, 0),
	CBTFX_FRAME(1, 16, 6, 1, FX_E_5, 0, 0, 0),
	CBTFX_FRAME(2, 16, 6, 2, FX_E_4, 0, 0, 0),
	CBTFX_FRAME(2, 16, 4, 1, FX_E_4, 0, 0, 0),
	CBTFX_FRAME(2, 16, 2, 0, FX_E_4, 0, 0, 0)
};