/*

	SFX_09

	Sound Effect File.

	Info:
		Length	:	16
		Bank	:	0

	This file was generated by hammer2cbt

*/
#ifndef __SFX_09_h_INCLUDE
#define __SFX_09_h_INCLUDE
#define SFX_09_Length 16
#define SFX_09_Bank 0
extern const unsigned char SFX_09[16][CBTFX_LENGTH];
#endif