/*

	SFX_01

	Sound Effect File.

	Info:
		Length			:	15
		Bank			:	0
		Priority		:	0
		Channels used	:	Duty channel 2

	This file was generated by hammer2cbt

*/
#ifndef __SFX_01_h_INCLUDE
#define __SFX_01_h_INCLUDE
#define SFX_01_Length 15
#define SFX_01_Bank 0
#define SFX_01_CH_Used 240
#define SFX_01_Priority 0
#define CBTFX_PLAY_SFX_01 CBTFX_init(&SFX_01[0][0], 15, 0, 240)
extern const unsigned char SFX_01[15][CBTFX_LENGTH];
#endif