/*

	SFX_02

	Sound Effect File.

	Info:
		Length			:	13
		Bank			:	0
		Priority		:	0
		Channels used	:	Duty channel 2 & Noise channel

	This file was generated by hammer2cbt

*/
#ifndef __SFX_02_h_INCLUDE
#define __SFX_02_h_INCLUDE
#define SFX_02_Length 13
#define SFX_02_Bank 0
#define SFX_02_CH_Used 255
#define SFX_02_Priority 0
#define CBTFX_PLAY_SFX_02 CBTFX_init(&SFX_02[0][0], 13, 0, 255)
extern const unsigned char SFX_02[13][CBTFX_LENGTH];
#endif