/*

	SFX_09

	Sound Effect File.

	Info:
		Length			:	17
		Bank			:	0
		Priority		:	0
		Channels used	:	Duty channel 2 & Noise channel

	This file was generated by hammer2cbt

*/
#ifndef __SFX_09_h_INCLUDE
#define __SFX_09_h_INCLUDE
#define SFX_09_Length 17
#define SFX_09_Bank 0
#define SFX_09_CH_Used 255
#define SFX_09_Priority 0
#define CBTFX_PLAY_SFX_09 CBTFX_init(&SFX_09[0][0], 17, 0, 255)
extern const unsigned char SFX_09[17][CBTFX_LENGTH];
#endif