/*

	SFX_00

	Sound Effect File.

	Info:
		Length	:	14
		Bank	:	0

	This file was generated by hammer2cbt

*/
#define SFX_00_Length 14
#define SFX_00_Bank 0
#include "../cbtfx.h"

const unsigned char SFX_00[14][CBTFX_LENGTH] = {
	CBTFX_FRAME(2, 17, 15, 0, FX_Gs2, 17, 15, 80),
	CBTFX_FRAME(1, 17, 15, 1, FX_Fs2, 17, 8, 48),
	CBTFX_FRAME(1, 17, 15, 1, FX_E_2, 17, 15, 112),
	CBTFX_FRAME(1, 17, 14, 2, FX_D_2, 17, 4, 48),
	CBTFX_FRAME(1, 17, 13, 2, FX_C_2, 17, 2, 32),
	CBTFX_FRAME(2, 17, 12, 2, FX_B_1, 17, 1, 16),
	CBTFX_FRAME(2, 17, 11, 2, FX_A_1, 0, 0, 0),
	CBTFX_FRAME(2, 1, 4, 0, FX_Gs2, 0, 0, 0),
	CBTFX_FRAME(1, 1, 4, 1, FX_Fs2, 0, 0, 0),
	CBTFX_FRAME(1, 1, 4, 1, FX_E_2, 0, 0, 0),
	CBTFX_FRAME(1, 16, 4, 2, FX_D_2, 0, 0, 0),
	CBTFX_FRAME(1, 16, 3, 2, FX_C_2, 0, 0, 0),
	CBTFX_FRAME(2, 16, 2, 2, FX_B_1, 0, 0, 0),
	CBTFX_FRAME(2, 16, 1, 2, FX_A_1, 0, 0, 0)
};