/*

	SFX_03

	Sound Effect File.

	Info:
		Length			:	25
		Bank			:	0
		Priority		:	0
		Channels used	:	Duty channel 2

	This file was generated by hammer2cbt

*/
#ifndef __SFX_03_h_INCLUDE
#define __SFX_03_h_INCLUDE
#define SFX_03_Length 25
#define SFX_03_Bank 0
#define SFX_03_CH_Used 240
#define SFX_03_Priority 0
#define CBTFX_PLAY_SFX_03 CBTFX_init(&SFX_03[0][0], 25, 0, 240)
extern const unsigned char SFX_03[25][CBTFX_LENGTH];
#endif