/*

	SFX_07

	Sound Effect File.

	Info:
		Length	:	31
		Bank	:	0

	This file was generated by hammer2cbt

*/
#define SFX_07_Length 31
#define SFX_07_Bank 0
#include "../cbtfx.h"

const unsigned char SFX_07[31][CBTFX_LENGTH] = {
	CBTFX_FRAME(2, 17, 15, 2, FX_E_1, 0, 0, 0),
	CBTFX_FRAME(2, 17, 15, 1, FX_E_1, 0, 0, 0),
	CBTFX_FRAME(2, 17, 15, 1, FX_C_2, 0, 0, 0),
	CBTFX_FRAME(2, 17, 15, 0, FX_C_2, 0, 0, 0),
	CBTFX_FRAME(2, 17, 15, 0, FX_Gs1, 0, 0, 0),
	CBTFX_FRAME(2, 17, 15, 1, FX_Gs1, 0, 0, 0),
	CBTFX_FRAME(2, 17, 15, 1, FX_E_2, 0, 0, 0),
	CBTFX_FRAME(2, 17, 15, 2, FX_E_2, 0, 0, 0),
	CBTFX_FRAME(2, 17, 15, 2, FX_C_2, 0, 0, 0),
	CBTFX_FRAME(2, 17, 15, 1, FX_C_2, 0, 0, 0),
	CBTFX_FRAME(2, 17, 15, 1, FX_Gs2, 0, 0, 0),
	CBTFX_FRAME(2, 17, 15, 0, FX_Gs2, 0, 0, 0),
	CBTFX_FRAME(2, 17, 15, 0, FX_Gs1, 0, 0, 0),
	CBTFX_FRAME(2, 17, 15, 1, FX_Gs1, 0, 0, 0),
	CBTFX_FRAME(2, 17, 15, 1, FX_C_3, 0, 0, 0),
	CBTFX_FRAME(2, 17, 15, 2, FX_C_3, 0, 0, 0),
	CBTFX_FRAME(2, 17, 14, 2, FX_Gs2, 0, 0, 0),
	CBTFX_FRAME(2, 17, 14, 1, FX_Gs2, 0, 0, 0),
	CBTFX_FRAME(2, 17, 13, 1, FX_E_3, 0, 0, 0),
	CBTFX_FRAME(2, 17, 12, 0, FX_E_3, 0, 0, 0),
	CBTFX_FRAME(2, 17, 11, 0, FX_C_3, 0, 0, 0),
	CBTFX_FRAME(2, 17, 10, 1, FX_C_3, 0, 0, 0),
	CBTFX_FRAME(2, 17, 9, 1, FX_Gs3, 0, 0, 0),
	CBTFX_FRAME(2, 17, 8, 2, FX_Gs3, 0, 0, 0),
	CBTFX_FRAME(2, 17, 7, 2, FX_E_3, 0, 0, 0),
	CBTFX_FRAME(2, 17, 6, 1, FX_E_3, 0, 0, 0),
	CBTFX_FRAME(2, 17, 5, 1, FX_C_4, 0, 0, 0),
	CBTFX_FRAME(2, 17, 4, 0, FX_C_4, 0, 0, 0),
	CBTFX_FRAME(4, 17, 3, 1, FX_Gs3, 0, 0, 0),
	CBTFX_FRAME(4, 17, 2, 2, FX_E_4, 0, 0, 0),
	CBTFX_FRAME(4, 17, 1, 1, FX_C_4, 0, 0, 0)
};