/*

	SFX_08

	Sound Effect File.

	Info:
		Length	:	20
		Bank	:	0

	This file was generated by hammer2cbt

*/
#ifndef __SFX_08_h_INCLUDE
#define __SFX_08_h_INCLUDE
#define SFX_08_Length 20
#define SFX_08_Bank 0
extern const unsigned char SFX_08[20][CBTFX_LENGTH];
#endif