/*

	SFX_09

	Sound Effect File.

	Info:
		Length			:	17
		Bank			:	0
		Priority		:	0
		Channels used	:	Duty channel 2 & Noise channel

	This file was generated by hammer2cbt

*/
#define SFX_09_Length 17
#define SFX_09_Bank 0
#define SFX_09_CH_Used 255
#define SFX_09_Priority 0
#define CBTFX_PLAY_SFX_09 CBTFX_init(&SFX_09[0][0], 17, 0, 255)
#include "../cbtfx.h"

const unsigned char SFX_09[17][CBTFX_LENGTH] = {
	CBTFX_FRAME(3, 17, 15, 0, FX_D_1, 17, 15, 128),
	CBTFX_FRAME(3, 17, 15, 2, FX_Cs0, 17, 6, 64),
	CBTFX_FRAME(3, 17, 15, 1, FX_C_0, 17, 3, 48),
	CBTFX_FRAME(3, 17, 15, 0, FX_C_0, 17, 1, 32),
	CBTFX_FRAME(3, 17, 15, 1, FX_C_0, 0, 0, 0),
	CBTFX_FRAME(3, 17, 15, 2, FX_C_0, 0, 0, 0),
	CBTFX_FRAME(3, 17, 15, 1, FX_C_0, 0, 0, 0),
	CBTFX_FRAME(3, 17, 15, 0, FX_C_0, 0, 0, 0),
	CBTFX_FRAME(3, 17, 15, 1, FX_C_0, 0, 0, 0),
	CBTFX_FRAME(2, 17, 12, 2, FX_Cs0, 0, 0, 0),
	CBTFX_FRAME(1, 17, 8, 2, FX_D_0, 0, 0, 0),
	CBTFX_FRAME(1, 17, 6, 2, FX_Ds0, 0, 0, 0),
	CBTFX_FRAME(1, 17, 4, 1, FX_E_0, 0, 0, 0),
	CBTFX_FRAME(1, 17, 2, 1, FX_F_0, 0, 0, 0),
	CBTFX_FRAME(1, 17, 1, 1, FX_Fs0, 0, 0, 0),
	CBTFX_FRAME(1, 17, 1, 1, FX_Gs0, 0, 0, 0)
};