/*

	SFX_01

	Sound Effect File.

	Info:
		Length			:	15
		Bank			:	0
		Priority		:	0
		Channels used	:	Duty channel 2

	This file was generated by hammer2cbt

*/
#define SFX_01_Length 15
#define SFX_01_Bank 0
#define SFX_01_CH_Used 240
#define SFX_01_Priority 0
#define CBTFX_PLAY_SFX_01 CBTFX_init(&SFX_01[0][0], 15, 0, 240)
#include "../cbtfx.h"

const unsigned char SFX_01[15][CBTFX_LENGTH] = {
	CBTFX_FRAME(1, 17, 15, 2, FX_E_1, 0, 0, 0),
	CBTFX_FRAME(1, 17, 15, 2, FX_Gs1, 0, 0, 0),
	CBTFX_FRAME(1, 17, 15, 2, FX_C_2, 0, 0, 0),
	CBTFX_FRAME(1, 17, 14, 2, FX_E_2, 0, 0, 0),
	CBTFX_FRAME(1, 17, 13, 2, FX_Gs2, 0, 0, 0),
	CBTFX_FRAME(1, 17, 12, 2, FX_C_3, 0, 0, 0),
	CBTFX_FRAME(1, 17, 11, 2, FX_E_3, 0, 0, 0),
	CBTFX_FRAME(1, 16, 4, 2, FX_E_1, 0, 0, 0),
	CBTFX_FRAME(1, 16, 4, 2, FX_Gs1, 0, 0, 0),
	CBTFX_FRAME(1, 16, 4, 2, FX_C_2, 0, 0, 0),
	CBTFX_FRAME(1, 1, 4, 2, FX_E_2, 0, 0, 0),
	CBTFX_FRAME(1, 1, 3, 2, FX_Gs2, 0, 0, 0),
	CBTFX_FRAME(1, 1, 2, 2, FX_C_3, 0, 0, 0),
	CBTFX_FRAME(1, 1, 1, 2, FX_E_3, 0, 0, 0)
};