/*

	SFX_08

	Sound Effect File.

	Info:
		Length			:	21
		Bank			:	0
		Priority		:	0
		Channels used	:	Noise channel

	This file was generated by hammer2cbt

*/
#define SFX_08_Length 21
#define SFX_08_Bank 0
#define SFX_08_CH_Used 15
#define SFX_08_Priority 0
#define CBTFX_PLAY_SFX_08 CBTFX_init(&SFX_08[0][0], 21, 0, 15)
#include "../cbtfx.h"

const unsigned char SFX_08[21][CBTFX_LENGTH] = {
	CBTFX_FRAME(2, 0, 0, 0, FX_E_3, 17, 15, 64),
	CBTFX_FRAME(2, 0, 0, 0, FX_E_3, 17, 15, 80),
	CBTFX_FRAME(2, 0, 0, 0, FX_E_3, 17, 15, 96),
	CBTFX_FRAME(2, 0, 0, 0, FX_E_3, 17, 15, 112),
	CBTFX_FRAME(2, 0, 0, 0, FX_E_3, 17, 15, 128),
	CBTFX_FRAME(2, 0, 0, 0, FX_E_3, 17, 5, 64),
	CBTFX_FRAME(2, 0, 0, 0, FX_E_3, 17, 5, 80),
	CBTFX_FRAME(2, 0, 0, 0, FX_E_3, 17, 5, 96),
	CBTFX_FRAME(2, 0, 0, 0, FX_E_3, 17, 5, 112),
	CBTFX_FRAME(2, 0, 0, 0, FX_E_3, 17, 5, 128),
	CBTFX_FRAME(2, 0, 0, 0, FX_E_3, 16, 3, 64),
	CBTFX_FRAME(2, 0, 0, 0, FX_E_3, 16, 3, 80),
	CBTFX_FRAME(2, 0, 0, 0, FX_E_3, 16, 3, 96),
	CBTFX_FRAME(2, 0, 0, 0, FX_E_3, 16, 3, 112),
	CBTFX_FRAME(2, 0, 0, 0, FX_E_3, 16, 3, 128),
	CBTFX_FRAME(2, 0, 0, 0, FX_E_3, 1, 2, 64),
	CBTFX_FRAME(2, 0, 0, 0, FX_E_3, 1, 2, 80),
	CBTFX_FRAME(2, 0, 0, 0, FX_E_3, 1, 2, 96),
	CBTFX_FRAME(2, 0, 0, 0, FX_E_3, 1, 2, 112),
	CBTFX_FRAME(2, 0, 0, 0, FX_E_3, 1, 2, 128)
};