/*

	SFX_07

	Sound Effect File.

	Info:
		Length			:	32
		Bank			:	0
		Priority		:	0
		Channels used	:	Duty channel 2

	This file was generated by hammer2cbt

*/
#ifndef __SFX_07_h_INCLUDE
#define __SFX_07_h_INCLUDE
#define SFX_07_Length 32
#define SFX_07_Bank 0
#define SFX_07_CH_Used 240
#define SFX_07_Priority 0
#define CBTFX_PLAY_SFX_07 CBTFX_init(&SFX_07[0][0], 32, 0, 240)
extern const unsigned char SFX_07[32][CBTFX_LENGTH];
#endif