/*

	SFX_08

	Sound Effect File.

	Info:
		Length			:	21
		Bank			:	0
		Priority		:	0
		Channels used	:	Noise channel

	This file was generated by hammer2cbt

*/
#ifndef __SFX_08_h_INCLUDE
#define __SFX_08_h_INCLUDE
#define SFX_08_Length 21
#define SFX_08_Bank 0
#define SFX_08_CH_Used 15
#define SFX_08_Priority 0
#define CBTFX_PLAY_SFX_08 CBTFX_init(&SFX_08[0][0], 21, 0, 15)
extern const unsigned char SFX_08[21][CBTFX_LENGTH];
#endif