/*

		SFX_04

		Sound Effect File.
		
		Info:
			Length			:	12
			Priority		:	0
			Channels used	:	Duty channel 2 & Noise channel
		
		This file was generated by hammer2cbt

	*/
	#ifndef __SFX_04_h_INCLUDE
#define __SFX_04_h_INCLUDE
#define CBTFX_PLAY_SFX_04 CBTFX_init(&SFX_04[0])
extern const unsigned char SFX_04[];
#endif