/*

	SFX_01

	Sound Effect File.

	Info:
		Length	:	14
		Bank	:	0

	This file was generated by hammer2cbt

*/
#ifndef __SFX_01_h_INCLUDE
#define __SFX_01_h_INCLUDE
#define SFX_01_Length 14
#define SFX_01_Bank 0
extern const unsigned char SFX_01[14][CBTFX_LENGTH];
#endif