/*

	SFX_04

	Sound Effect File.

	Info:
		Length			:	13
		Bank			:	0
		Priority		:	0
		Channels used	:	Duty channel 2 & Noise channel

	This file was generated by hammer2cbt

*/
#define SFX_04_Length 13
#define SFX_04_Bank 0
#define SFX_04_CH_Used 255
#define SFX_04_Priority 0
#define CBTFX_PLAY_SFX_04 CBTFX_init(&SFX_04[0][0], 13, 0, 255)
#include "../cbtfx.h"

const unsigned char SFX_04[13][CBTFX_LENGTH] = {
	CBTFX_FRAME(1, 17, 15, 2, FX_C_3, 17, 8, 80),
	CBTFX_FRAME(2, 17, 15, 2, FX_C_2, 17, 3, 48),
	CBTFX_FRAME(1, 17, 15, 2, FX_E_3, 17, 3, 32),
	CBTFX_FRAME(3, 17, 15, 2, FX_E_2, 17, 2, 32),
	CBTFX_FRAME(2, 17, 15, 2, FX_E_2, 17, 2, 32),
	CBTFX_FRAME(2, 17, 2, 2, FX_E_2, 17, 1, 16),
	CBTFX_FRAME(1, 16, 4, 2, FX_E_2, 1, 3, 80),
	CBTFX_FRAME(2, 16, 4, 2, FX_C_2, 1, 2, 48),
	CBTFX_FRAME(1, 16, 4, 2, FX_E_3, 1, 1, 32),
	CBTFX_FRAME(3, 16, 4, 2, FX_E_2, 0, 0, 0),
	CBTFX_FRAME(2, 16, 4, 2, FX_E_2, 0, 0, 0),
	CBTFX_FRAME(2, 16, 1, 2, FX_E_2, 0, 0, 0)
};