/*

	SFX_03

	Sound Effect File.

	Info:
		Length			:	25
		Bank			:	0
		Priority		:	0
		Channels used	:	Duty channel 2

	This file was generated by hammer2cbt

*/
#define SFX_03_Length 25
#define SFX_03_Bank 0
#define SFX_03_CH_Used 240
#define SFX_03_Priority 0
#define CBTFX_PLAY_SFX_03 CBTFX_init(&SFX_03[0][0], 25, 0, 240)
#include "../cbtfx.h"

const unsigned char SFX_03[25][CBTFX_LENGTH] = {
	CBTFX_FRAME(1, 17, 15, 0, FX_E_5, 0, 0, 0),
	CBTFX_FRAME(3, 17, 15, 2, FX_E_4, 0, 0, 0),
	CBTFX_FRAME(1, 17, 15, 0, FX_Fs5, 0, 0, 0),
	CBTFX_FRAME(3, 17, 15, 2, FX_Fs4, 0, 0, 0),
	CBTFX_FRAME(1, 17, 15, 0, FX_Gs5, 0, 0, 0),
	CBTFX_FRAME(3, 17, 15, 2, FX_Gs4, 0, 0, 0),
	CBTFX_FRAME(1, 17, 5, 0, FX_E_5, 0, 0, 0),
	CBTFX_FRAME(3, 17, 5, 2, FX_E_4, 0, 0, 0),
	CBTFX_FRAME(1, 17, 5, 0, FX_Fs5, 0, 0, 0),
	CBTFX_FRAME(3, 17, 5, 2, FX_Fs4, 0, 0, 0),
	CBTFX_FRAME(1, 17, 5, 0, FX_Gs5, 0, 0, 0),
	CBTFX_FRAME(3, 17, 5, 2, FX_Gs4, 0, 0, 0),
	CBTFX_FRAME(1, 17, 2, 0, FX_E_5, 0, 0, 0),
	CBTFX_FRAME(3, 17, 2, 2, FX_E_4, 0, 0, 0),
	CBTFX_FRAME(1, 17, 2, 0, FX_Fs5, 0, 0, 0),
	CBTFX_FRAME(3, 17, 2, 2, FX_Fs4, 0, 0, 0),
	CBTFX_FRAME(1, 17, 2, 0, FX_Gs5, 0, 0, 0),
	CBTFX_FRAME(3, 17, 2, 2, FX_Gs4, 0, 0, 0),
	CBTFX_FRAME(1, 16, 1, 0, FX_E_5, 0, 0, 0),
	CBTFX_FRAME(3, 16, 1, 2, FX_E_4, 0, 0, 0),
	CBTFX_FRAME(1, 16, 1, 0, FX_Fs5, 0, 0, 0),
	CBTFX_FRAME(3, 16, 1, 2, FX_Fs4, 0, 0, 0),
	CBTFX_FRAME(1, 16, 1, 0, FX_Gs5, 0, 0, 0),
	CBTFX_FRAME(3, 16, 1, 2, FX_Gs4, 0, 0, 0)
};