/*

	SFX_00

	Sound Effect File.

	Info:
		Length	:	14
		Bank	:	0

	This file was generated by hammer2cbt

*/
#ifndef __SFX_00_h_INCLUDE
#define __SFX_00_h_INCLUDE
#define SFX_00_Length 14
#define SFX_00_Bank 0
extern const unsigned char SFX_00[14][CBTFX_LENGTH];
#endif