/*

		SFX_09

		Sound Effect File.
		
		Info:
			Length			:	16
			Priority		:	0
			Channels used	:	Duty channel 2 & Noise channel
		
		This file was generated by hammer2cbt

	*/
	#ifndef __SFX_09_h_INCLUDE
#define __SFX_09_h_INCLUDE
#define CBTFX_PLAY_SFX_09 CBTFX_init(&SFX_09[0])
extern const unsigned char SFX_09[];
#endif