/*

	SFX_03

	Sound Effect File.

	Info:
		Length	:	24
		Bank	:	0

	This file was generated by hammer2cbt

*/
#ifndef __SFX_03_h_INCLUDE
#define __SFX_03_h_INCLUDE
#define SFX_03_Length 24
#define SFX_03_Bank 0
extern const unsigned char SFX_03[24][CBTFX_LENGTH];
#endif