/*

	SFX_04

	Sound Effect File.

	Info:
		Length			:	13
		Bank			:	0
		Priority		:	0
		Channels used	:	Duty channel 2 & Noise channel

	This file was generated by hammer2cbt

*/
#ifndef __SFX_04_h_INCLUDE
#define __SFX_04_h_INCLUDE
#define SFX_04_Length 13
#define SFX_04_Bank 0
#define SFX_04_CH_Used 255
#define SFX_04_Priority 0
#define CBTFX_PLAY_SFX_04 CBTFX_init(&SFX_04[0][0], 13, 0, 255)
extern const unsigned char SFX_04[13][CBTFX_LENGTH];
#endif